using System.Text;

namespace AiTrace.Pro.Verification;

public static class EvidenceReadmeWriter
{
    public static string BuildReadmeText(
        ComplianceVerificationSummary summary,
        VerificationPolicy policy,
        VerificationScope scope)
    {
        var sb = new StringBuilder();

        sb.AppendLine("AI Decision Evidence Bundle");
        sb.AppendLine("==========================");
        sb.AppendLine();
        sb.AppendLine("This folder contains an exportable evidence bundle generated by AiTrace.NET.");
        sb.AppendLine("It is intended for audits, legal review, and regulatory inquiries.");
        sb.AppendLine();

        sb.AppendLine("1) Contents");
        sb.AppendLine("-----------");
        sb.AppendLine("- audit/                 : copied audit JSON records (scoped)");
        sb.AppendLine("- compliance_report.txt  : human-readable verification report");
        sb.AppendLine("- compliance_report.json : machine-readable verification report");
        sb.AppendLine("- public_key.pem         : public key used for signature verification (if included)");
        sb.AppendLine("- manifest.txt           : list of included audit files (if enabled)");
        sb.AppendLine();

        sb.AppendLine("2) Verification Summary");
        sb.AppendLine("----------------------");
        sb.AppendLine($"Status: {summary.Status}");
        sb.AppendLine($"Valid: {(summary.IsValid ? "YES" : "NO")}");
        sb.AppendLine($"IntegrityVerified: {(summary.IntegrityVerified ? "YES" : "NO")}");
        sb.AppendLine($"ChainVerified: {(summary.ChainVerified ? "YES" : "NO")}");
        sb.AppendLine($"SignatureRequired: {(summary.SignatureRequired ? "YES" : "NO")}");
        sb.AppendLine($"AnySignaturePresent: {(summary.AnySignaturePresent ? "YES" : "NO")}");
        sb.AppendLine($"SignatureStatus: {summary.SignatureStatus}");
        sb.AppendLine($"FilesVerified: {summary.FilesVerified}");
        sb.AppendLine($"RecordsVerified: {summary.RecordsVerified}");
        sb.AppendLine($"TimeRangeUtc: {Fmt(summary.FirstTimestampUtc)} to {Fmt(summary.LastTimestampUtc)}");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(summary.Reason))
        {
            sb.AppendLine("Reason");
            sb.AppendLine("------");
            sb.AppendLine(summary.Reason);
            sb.AppendLine();
        }

        sb.AppendLine("3) Export Policy");
        sb.AppendLine("---------------");
        sb.AppendLine($"RequireSignatures: {(policy.RequireSignatures ? "YES" : "NO")}");
        sb.AppendLine($"RequireChainIntegrity: {(policy.RequireChainIntegrity ? "YES" : "NO")}");
        sb.AppendLine($"FailOnMissingFiles: {(policy.FailOnMissingFiles ? "YES" : "NO")}");
        sb.AppendLine($"AllowStartMidChain: {(policy.AllowStartMidChain ? "YES" : "NO")}");
        sb.AppendLine();

        sb.AppendLine("4) Export Scope (UTC)");
        sb.AppendLine("---------------------");
        sb.AppendLine($"FromUtc: {Fmt(scope.FromUtc)}");
        sb.AppendLine($"ToUtc:   {Fmt(scope.ToUtc)}");
        sb.AppendLine();

        sb.AppendLine("5) How to re-verify independently");
        sb.AppendLine("--------------------------------");
        sb.AppendLine("- Verify hashes for each record.");
        sb.AppendLine("- Verify PrevHashSha256 chain integrity (if required).");
        sb.AppendLine("- Verify signatures using public_key.pem (if signatures are required/present).");
        sb.AppendLine();
        sb.AppendLine("Generated by AiTrace.NET (Pro verification).");

        return sb.ToString();
    }

    private static string Fmt(DateTimeOffset? v)
        => v.HasValue ? v.Value.ToUniversalTime().ToString("O") : "(unknown)";
}